### ISSUE TITLE
Miller Casting Replied

### ISSUE THREAD

**Issue by BMcD-MES** [marka2g/marka2g#1]
Log into dreamhost and reply as Daniel. 
Then ask if Eliza Mondragon <Elizam@millercastings.com> is the new contact for accounts payable or if there is some other email address we should you in place of Roberta Barron.

Then update the invoice and send it along. Work with me on the update. Some things need to change.

**Comment by marka2g** [comment]
Replied to Phil.
Phil replied with, "Eliza is still the correct contact.  I would suggest sending it to [ap@millercastings.com](mailto:ap@millercastings.com) instead of directly to her"

Daniel Clark adjusted the invoice to cc: Eliza Mondragon and then sent it to ap@millercastings.com with a cc to Phil N and bcc to Brian M and Mark S
